/**
 * Schemas: data structure definitions for Paradoc
 *
 * These types correspond to JSON schemas defined in @paradoc/schemas.
 * For runtime types (filled forms, parties, etc.), see ../runtime
 */

// Primitives (correspond to schemas in @paradoc/schemas)
export type {
  Money,
  Address,
  Phone,
  Person,
  Organization,
  Coordinate,
  Bbox,
  Duration,
  Identification,
  Metadata,
  Signature,
  Attachment,
} from "./primitives";

// Artifact types (includes shared expression types)
export type {
  // Expression types
  CondExpr,
  BaseExpression,
  BooleanExpression,
  StringExpression,
  NumberExpression,
  IntegerExpression,
  PercentageExpression,
  RatingExpression,
  DateExpression,
  TimeExpression,
  DatetimeExpression,
  DurationExpression,
  MoneyExpressionValue,
  AddressExpressionValue,
  PhoneExpressionValue,
  CoordinateExpressionValue,
  BboxExpressionValue,
  PersonExpressionValue,
  OrganizationExpressionValue,
  IdentificationExpressionValue,
  MoneyExpression,
  AddressExpression,
  PhoneExpression,
  CoordinateExpression,
  BboxExpression,
  PersonExpression,
  OrganizationExpression,
  IdentificationExpression,
  ScalarExpression,
  ObjectExpression,
  Expression,
  ScalarExpressionType,
  ObjectExpressionType,
  ExpressionType,
  DefsSection,
  // Rules types
  RuleSeverity,
  ValidationRule,
  RulesSection,
  // Shared types
  ArtifactBase,
  InlineContentRef,
  FileContentRef,
  ContentRef,
  SignatureBlockType,
  SignatureBlock,
  Layer,
  InlineLayer,
  FileLayer,
  Bindings,
  // Document
  Document,
  // Checklist
  BooleanStatusSpec,
  EnumStatusOption,
  EnumStatusSpec,
  StatusSpec,
  ChecklistItem,
  Checklist,
  // Bundle
  BundleContentItem,
  InlineBundleItem,
  PathBundleItem,
  RegistryBundleItem,
  Bundle,
  // Form
  Form,
  BaseField,
  FieldsetField,
  FormField,
  TextField,
  BooleanField,
  NumberField,
  CoordinateField,
  BboxField,
  MoneyField,
  AddressField,
  PhoneField,
  DurationField,
  EmailField,
  UuidField,
  UriField,
  EnumField,
  DateField,
  DatetimeField,
  TimeField,
  PersonField,
  OrganizationField,
  IdentificationField,
  MultiselectField,
  PercentageField,
  RatingField,
  FormFieldset,
  FormAnnex,
  FormParty,
  FormSignature,
  // Unions
  Artifact,
} from "./artifacts";
