/**
 * The parity report: the shape the suite writes, and the table it prints.
 *
 * The report is a deliverable in its own right, not a by-product of the
 * assertions. The README quotes it, so every number in it is stated per page, in one
 * place, with the units and the thresholds it was measured against alongside —
 * a percentage with no tolerance and no resolution beside it cannot be checked
 * by anyone reading the note later.
 *
 * It is written to a gitignored directory. A measurement of one machine's Chrome
 * against one build of the engine is evidence for a run, not a file to keep in
 * the repository and let rot.
 */

import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import type { PageDimensions } from "../../src/lib/tokens";
import type { PdfAdapterName } from "../../src/pdf";
import type { Branding, DataSet } from "./preview";

/** Which side decided the page breaks. */
export type PaginationMode = "engine" | "hint";

/** Where the report and its images go. Gitignored; regenerated by every run. */
export const REPORT_DIRECTORY = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "parity"
);

/** One page of one run. */
export interface PageReport {
  number: number;
  /**
   * The first keep on the page that is the keep's own place in the flow and
   * carries text. A repeated header is a copy, and a keep with no text — the
   * masthead's logo is one — cannot be named from a PDF at all, so neither can
   * be the keep a page is identified by.
   */
  previewFirstKeep: string | null;
  pdfFirstKeep: string | null;
  firstKeepMatches: boolean;
  /** Share of the page the preview paints on, as a percentage. */
  inkPercent: number;
  /** The specification's measure: differing pixels as a percentage of the page. */
  differingPercent: number;
  /** The same count with no tolerance at all. */
  strictDifferingPercent: number;
  /**
   * True when the raw count is under the specification's original one percent.
   * Recorded for every page of every adapter, because the question a second
   * engine was added to answer is whether that clause is reachable at all.
   */
  underOnePercent: boolean;
  /** What one pixel of vertical drift costs, measured on the preview alone. */
  shiftFloorPercent: number;
  /** What still differs once each band may slide vertically. */
  alignedPercent: number;
  /** The largest vertical slide a band needed, in pixels. */
  driftPixels: number;
  /**
   * True when that slide sat at the edge of the search, so the drift is a floor
   * rather than a measurement. A saturated page is never a passing page.
   */
  driftSaturated: boolean;
  /** File name of the difference picture in the report directory. */
  image: string;
}

/** One data set rendered one way, compared page by page. */
export interface RunReport {
  /** Which engine wrote the PDF. */
  adapter: PdfAdapterName;
  dataSet: DataSet;
  /** Which token set the document was branded with. */
  branding: Branding;
  /** The paper that token set chose, which both sides were compared at. */
  paper: PageDimensions;
  mode: PaginationMode;
  previewPages: number;
  pdfPages: number;
  pageCountMatches: boolean;
  firstKeepsMatch: boolean;
  /** True when every page of the run is inside the residual and drift limits. */
  meetsCriteria: boolean;
  /** Hints the render could not honour. Empty is the only passing value. */
  unknownBreaks: string[];
  unknownRepeats: string[];
  /** The worst page's raw differing percentage. Recorded, not asserted. */
  worstDifferingPercent: number;
  /** The worst page's residual once each band is aligned. Asserted in hint mode. */
  worstAlignedPercent: number;
  /** The worst page's band drift, in pixels. Asserted in hint mode. */
  worstDriftPixels: number;
  /** True when every page's raw difference is under one percent. Recorded. */
  everyPageUnderOnePercent: boolean;
  pages: PageReport[];
}

/** The run that proves the measurement responds to a change on one side only. */
export interface SensitivityReport {
  adapter: PdfAdapterName;
  dataSet: DataSet;
  branding: Branding;
  mode: PaginationMode;
  page: number;
  css: string;
  /** The raw difference, before and after the change. Recorded, not asserted. */
  beforePercent: number;
  afterPercent: number;
  /** The residual the criteria read, before and after. The change must cross it. */
  beforeAlignedPercent: number;
  afterAlignedPercent: number;
}

/** Everything one invocation of the suite measured. */
export interface ParityReport {
  generatedAt: string;
  /**
   * The paper the unbranded runs are compared at, in CSS pixels. A branded run
   * states its own in `paper`, because a token set may choose another.
   */
  geometry: PageDimensions;
  /** How much larger than that both sides were drawn before being averaged down. */
  captureScale: number;
  /** Grayscale levels a pixel may move by, out of 255, before it counts. */
  tolerance: number;
  /** Residual a page may carry once each band is aligned, as a percentage. */
  residualThresholdPercent: number;
  /** How far a band may sit from its counterpart, in pixels. */
  driftLimitPixels: number;
  runs: RunReport[];
  sensitivity: SensitivityReport | null;
}

/** A percentage to two places, so a report never carries false precision. */
export function percent(part: number, whole: number): number {
  return Math.round((part / whole) * 10_000) / 100;
}

/** Empties the report directory and writes the report and its pictures into it. */
export function writeReport(report: ParityReport, images: Map<string, string>): string {
  rmSync(REPORT_DIRECTORY, { recursive: true, force: true });
  mkdirSync(REPORT_DIRECTORY, { recursive: true });

  for (const [name, dataUrl] of images) {
    const base64 = dataUrl.slice(dataUrl.indexOf(",") + 1);
    writeFileSync(join(REPORT_DIRECTORY, name), Buffer.from(base64, "base64"));
  }

  const path = join(REPORT_DIRECTORY, "parity-report.json");
  writeFileSync(path, `${JSON.stringify(report, null, 2)}\n`);
  return path;
}

/** One row of the printed table, already padded. */
function row(cells: readonly string[], widths: readonly number[]): string {
  return cells.map((cell, index) => cell.padEnd(widths[index]!)).join("  ").trimEnd();
}

/** The per-page table, printed so a person reading the run can check it. */
export function printReport(report: ParityReport): void {
  const lines: string[] = [];
  lines.push("");
  lines.push(
    `Parity at ${report.geometry.widthPx} x ${report.geometry.heightPx} CSS px unless a run ` +
      `says otherwise, drawn at ${report.captureScale}x and averaged down, grayscale, ` +
      `tolerance ${report.tolerance}/255.`
  );
  lines.push(
    `A page passes on aligned% under ${report.residualThresholdPercent} and drift within ` +
      `${report.driftLimitPixels} px. diff% and strict% are recorded, not asserted, and <1% ` +
      `says whether diff% clears the specification's original clause. ` +
      `A + on drift means the alignment search saturated, so that figure is a floor.`
  );

  // One table per adapter, because the two are separate answers to separate
  // questions and a single table interleaving them reads as one measurement.
  const adapters = [...new Set(report.runs.map((run) => run.adapter))];
  for (const adapter of adapters) {
    lines.push("");
    lines.push(`--- ${adapter} ---`);

    for (const run of report.runs.filter((candidate) => candidate.adapter === adapter)) {
      lines.push("");
      lines.push(
        `${run.dataSet} / ${run.branding} tokens / ${run.mode} breaks on ` +
          `${run.paper.widthPx}x${run.paper.heightPx}: preview ${run.previewPages} pages, ` +
          `PDF ${run.pdfPages} pages` +
          (run.unknownBreaks.length > 0 ? `, stale breaks ${run.unknownBreaks.join(",")}` : "") +
          (run.unknownRepeats.length > 0 ? `, stale repeats ${run.unknownRepeats.join(",")}` : "")
      );

      const header = [
        "page",
        "preview first keep",
        "pdf first keep",
        "same",
        "ink%",
        "diff%",
        "<1%",
        "strict%",
        "1px floor%",
        "aligned%",
        "drift px",
      ];
      const body = run.pages.map((page) => [
        String(page.number),
        page.previewFirstKeep ?? "-",
        page.pdfFirstKeep ?? "-",
        page.firstKeepMatches ? "yes" : "NO",
        page.inkPercent.toFixed(2),
        page.differingPercent.toFixed(2),
        page.underOnePercent ? "yes" : "no",
        page.strictDifferingPercent.toFixed(2),
        page.shiftFloorPercent.toFixed(2),
        page.alignedPercent.toFixed(2),
        `${page.driftPixels}${page.driftSaturated ? "+" : ""}`,
      ]);
      const widths = header.map((cell, index) =>
        Math.max(cell.length, ...body.map((cells) => cells[index]!.length))
      );
      lines.push(row(header, widths));
      for (const cells of body) lines.push(row(cells, widths));
    }
  }

  if (report.sensitivity !== null) {
    const check = report.sensitivity;
    lines.push("");
    lines.push(
      `A style change on the preview alone (${check.css}) moved ` +
        `${check.adapter} ${check.dataSet} / ${check.branding} tokens / ${check.mode} ` +
        `page ${check.page} from ` +
        `${check.beforeAlignedPercent.toFixed(2)}% to ` +
        `${check.afterAlignedPercent.toFixed(2)}% aligned, which fails the criteria ` +
        `(raw difference ${check.beforePercent.toFixed(2)}% to ${check.afterPercent.toFixed(2)}%).`
    );
  }

  lines.push("");
  console.log(lines.join("\n"));
}
