/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LlmsDotmdxDocsSplatRouteImport } from './routes/llms[.]mdx.docs.$'
import { Route as ApiOgDocsSplatRouteImport } from './routes/api/og/docs/$'

const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgDocsSplatRoute = ApiOgDocsSplatRouteImport.update({
  id: '/api/og/docs/$',
  path: '/api/og/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/api/og/docs/$': typeof ApiOgDocsSplatRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/api/og/docs/$': typeof ApiOgDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/api/og/docs/$': typeof ApiOgDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/llms-full.txt'
    | '/api/search'
    | '/llms.mdx/docs/$'
    | '/api/og/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/llms-full.txt'
    | '/api/search'
    | '/llms.mdx/docs/$'
    | '/api/og/docs/$'
  id:
    | '__root__'
    | '/$'
    | '/llms-full.txt'
    | '/api/search'
    | '/llms.mdx/docs/$'
    | '/api/og/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute
  ApiOgDocsSplatRoute: typeof ApiOgDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/docs/$': {
      id: '/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/docs/$': {
      id: '/api/og/docs/$'
      path: '/api/og/docs/$'
      fullPath: '/api/og/docs/$'
      preLoaderRoute: typeof ApiOgDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
  ApiOgDocsSplatRoute: ApiOgDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
