/**
 * @paradoc/format
 *
 * Immutable, locale-aware presentation of structured artifact values.
 *
 * This package owns display formatting only. It does not parse localized
 * input, serialize stored artifacts, convert currencies, or apply business
 * validation rules.
 */

export {
	defaultFormatter,
	createFormatter,
	formatAddress,
	formatAttachment,
	formatBbox,
	formatCoordinate,
	formatDate,
	formatDatetime,
	formatDuration,
	formatIdentification,
	formatMoney,
	formatNumber,
	formatPercentage,
	formatOrganization,
	formatParty,
	formatPerson,
	formatPhone,
	formatSignature,
	formatTime,
	formatValue,
	safeFormatAddress,
	safeFormatAttachment,
	safeFormatBbox,
	safeFormatDate,
	safeFormatDatetime,
	safeFormatDuration,
	safeFormatCoordinate,
	safeFormatIdentification,
	safeFormatMoney,
	safeFormatNumber,
	safeFormatOrganization,
	safeFormatParty,
	safeFormatPerson,
	safeFormatPhone,
	safeFormatPercentage,
	safeFormatSignature,
	safeFormatValue,
	safeFormatTime,
} from './formatter'

export { FormatConfigurationError, FormatError, isFormatError } from './errors'

export {
	FORMAT_KINDS,
	type AttachmentFormatOptions,
	type BboxFormatOptions,
	type CaptureFormatImplementation,
	type CaptureFormatImplementationContext,
	type CaptureFormatKind,
	type CaptureValueByKind,
	type AddressFormatOptions,
	type AddressLayoutContext,
	type AddressLayoutFormatter,
	type AddressLayoutPolicy,
	type FormatCallOptions,
	type ContactFormatImplementation,
	type ContactFormatImplementationContext,
	type ContactFormatKind,
	type ContactValueByKind,
	type CoordinateFormatOptions,
	type DateFormatOptions,
	type DatetimeFormatOptions,
	type DurationFormatOptions,
	type FormatImplementation,
	type FormatImplementationContext,
	type FormatInputByKind,
	type FormatIssue,
	type FormatKind,
	type FormatOptionsByKind,
	type FormatResult,
	type FormatStatus,
	type FormattedResult,
	type Formatter,
	type FormatterCacheBucketStats,
	type FormatterCacheStats,
	type FormatterMessages,
	type FormatterOptions,
	type FormatterOverrides,
	type IdentificationFormatOptions,
	type MoneyFormatOptions,
	type NumberFormatOptions,
	type OrganizationFormatOptions,
	type NumericFormatKind,
	type NumericValueByKind,
	type PartyFormatOptions,
	type PersonFormatOptions,
	type PhoneFormatOptions,
	type PercentageFormatOptions,
	type TemporalFormatImplementation,
	type TemporalFormatImplementationContext,
	type TemporalFormatKind,
	type TemporalFormatOptions,
	type TemporalValueByKind,
	type TimeFormatOptions,
	type SignatureFormatOptions,
	type UnformattedResult,
	type UnsupportedLocalePolicy,
} from './types'
