/**
 * The components page and the registry the site serves say the same thing.
 *
 * The registry under `public/r/` is generated by `pnpm registry:build` in
 * the private `@paradoc/components` workspace; the page listing it is written by hand, because a table of
 * one-line descriptions reads better than a generated one. That split is only
 * safe while something checks it, so this does: every item the site serves is
 * listed, nothing is listed that is not served, and each row links to the file
 * a consumer would actually fetch.
 */
import { readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, test } from 'vitest'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const registryDir = path.join(root, 'public/r')
const page = readFileSync(path.join(root, 'content/docs/components/index.mdx'), 'utf8')
const installationPage = readFileSync(
  path.join(root, 'content/docs/components/installation.mdx'),
  'utf8',
)
/** Names with their own reference page, linked internally instead of to the registry JSON. */
const referencePages = new Set([
  'bundle',
  'document',
  'field',
  'keep-together',
  'pages',
  'paper',
  'part',
  'pdf-pages',
  'qr-code',
  'section',
  'signature',
  'table',
  'totals',
])

/** Blocks with their own reference page, nested under Components' Blocks group. */
const blockReferencePages = new Set([
  'invoice',
  'purchase-order',
  'vendor-packet',
  'engagement-letter',
])

interface RegistryIndex {
  name: string
  homepage: string
  items: { name: string; type: string; description: string }[]
}

const index = JSON.parse(
  readFileSync(path.join(registryDir, 'registry.json'), 'utf8'),
) as RegistryIndex

describe('the served registry', () => {
  test('is served from this site', () => {
    expect(index.homepage).toBe('https://docs.paradoc.dev')
    expect(index.name).toBe('paradoc')
  })

  test('has one document per item, and no extras', () => {
    const served = readdirSync(registryDir)
      .filter((entry) => entry.endsWith('.json') && entry !== 'registry.json')
      .map((entry) => entry.replace(/\.json$/, ''))
      .sort()

    expect(served).toEqual(index.items.map((item) => item.name).sort())
  })
})

describe('the components page', () => {
  test('lists every item, linked to its reference page or the file the CLI fetches', () => {
    for (const item of index.items) {
      const link = referencePages.has(item.name)
        ? `[\`${item.name}\`](/components/${item.name})`
        : blockReferencePages.has(item.name)
          ? `[\`${item.name}\`](/components/blocks/${item.name})`
          : `[\`${item.name}\`](https://docs.paradoc.dev/r/${item.name}.json)`
      expect(page, `${item.name} is served but not listed`).toContain(link)
    }
  })

  test('lists nothing the registry does not serve', () => {
    const registryLinked = [
      ...page.matchAll(/\[`([a-z-]+)`\]\(https:\/\/docs\.paradoc\.dev\/r\//g),
    ].map((match) => match[1])
    const pageLinked = [...page.matchAll(/\[`([a-z-]+)`\]\(\/components\//g)].map(
      (match) => match[1],
    )
    const listed = [...registryLinked, ...pageLinked]
    const served = new Set(index.items.map((item) => item.name))

    expect(listed.length).toBeGreaterThan(0)
    for (const name of listed) {
      expect(served.has(name ?? ''), `${name} is listed but not served`).toBe(true)
    }
  })

  test('names the namespace and the URL template a consumer registers', () => {
    expect(installationPage).toContain('"@paradoc": "https://docs.paradoc.dev/r/{name}.json"')
  })
})
