/**
 * Tests for renderPdf function with field bindings
 */

import { describe, test, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { PDFDocument } from 'pdf-lib'
import { renderPdf } from '../src/render'
import type { Form } from '@paradoc/core'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

describe('renderPdf with bindings', () => {
  const testData = {
    name: 'Fluffy',
    species: 'cat',
    weight: 12,
    hasVaccination: true,
  }

  const formDefinition: Form = {
    kind: 'form',
    name: 'pet-addendum-2',
    version: '1.0.0',
    title: 'Pet Addendum',
    fields: {
      name: {
        type: 'text',
        label: 'Pet Name',
      },
      species: {
        type: 'enum',
        enum: ['dog', 'cat', 'bird', 'rabbit', 'hamster'],
        label: 'Species',
      },
      weight: {
        type: 'number',
        label: 'Weight (lbs)',
      },
      hasVaccination: {
        type: 'boolean',
        label: 'Has Vaccination',
      },
    },
  }

  // Bindings format: { pdfFieldName: formDataExpression }
  // Keys are the field names in the PDF, values are the form data paths
  const bindings = {
    pet_name: 'name',
    SPECIES: 'species',
    petWeight: 'weight',
    is_vaccinated: 'hasVaccination',
  }

  test('renders PDF template with pet data using bindings', async () => {
    const templatePath = path.join(__dirname, 'fixtures', 'pet-addendum-2.pdf')

    if (!fs.existsSync(templatePath)) {
      console.log('⚠️  No pet-addendum-2.pdf found in tests/fixtures/')
      return
    }

    // Read template
    const template = fs.readFileSync(templatePath)
    expect(template).toBeDefined()
    expect(template.length).toBeGreaterThan(0)

    // Render with bindings
    const output = await renderPdf({
      template: new Uint8Array(template),
      form: formDefinition,
      data: testData,
      bindings,
    })

    expect(output).toBeDefined()
    expect(output.length).toBeGreaterThan(0)
    expect(output).toBeInstanceOf(Uint8Array)

    // Write output to file
    const outputPath = path.join(__dirname, 'output', 'pet-addendum-2-rendered.pdf')

    // Create output directory if it doesn't exist
    const outputDir = path.dirname(outputPath)
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true })
    }

    fs.writeFileSync(outputPath, output)
    console.log('Rendered PDF file written to output/pet-addendum-2-rendered.pdf')
  })
})

describe('renderPdf with multiselect bindings', () => {
  // Build a self-contained PDF fixture with one checkbox per (field:value)
  // pair so we can exercise the multiselect code path without depending on
  // an external fixture file. Mirrors how spec-variant artifacts are
  // generated by design-pdf.
  async function buildMultiselectFixture(): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create()
    const page = pdfDoc.addPage([612, 792])
    const form = pdfDoc.getForm()

    // Multiselect field: recordTypes (3 values)
    const recordTypeValues = ['clinic_visit_notes', 'lab_results', 'discharge_summary']
    let y = 700
    for (const value of recordTypeValues) {
      const cb = form.createCheckBox(`recordTypes:${value}`)
      cb.addToPage(page, { x: 50, y, width: 12, height: 12 })
      y -= 20
    }

    // Enum field: status (2 values) — sanity check that enum still works
    for (const value of ['active', 'inactive']) {
      const cb = form.createCheckBox(`status:${value}`)
      cb.addToPage(page, { x: 50, y, width: 12, height: 12 })
      y -= 20
    }

    return await pdfDoc.save()
  }

  const formDefinition: Form = {
    kind: 'form',
    name: 'multiselect-fixture',
    version: '1.0.0',
    title: 'Multiselect Fixture',
    fields: {
      recordTypes: {
        type: 'multiselect',
        enum: ['clinic_visit_notes', 'lab_results', 'discharge_summary'],
        label: 'Record types',
      },
      status: {
        type: 'enum',
        enum: ['active', 'inactive'],
        label: 'Status',
      },
    },
  }

  const bindings = {
    'recordTypes:clinic_visit_notes': 'recordTypes:clinic_visit_notes',
    'recordTypes:lab_results': 'recordTypes:lab_results',
    'recordTypes:discharge_summary': 'recordTypes:discharge_summary',
    'status:active': 'status:active',
    'status:inactive': 'status:inactive',
  }

  test('checks each multiselect-value checkbox iff the value is in the array', async () => {
    const template = await buildMultiselectFixture()

    const output = await renderPdf({
      template,
      form: formDefinition,
      data: {
        recordTypes: ['lab_results', 'discharge_summary'],
        status: 'active',
      },
      bindings,
    })

    const rendered = await PDFDocument.load(output)
    const form = rendered.getForm()

    // Multiselect: only the boxes whose qualifier appears in the array should be checked
    expect(form.getCheckBox('recordTypes:clinic_visit_notes').isChecked()).toBe(false)
    expect(form.getCheckBox('recordTypes:lab_results').isChecked()).toBe(true)
    expect(form.getCheckBox('recordTypes:discharge_summary').isChecked()).toBe(true)

    // Enum (regression): unchanged behavior — only the matching value's box checked
    expect(form.getCheckBox('status:active').isChecked()).toBe(true)
    expect(form.getCheckBox('status:inactive').isChecked()).toBe(false)
  })

  test('leaves all multiselect checkboxes unchecked when the array is empty', async () => {
    const template = await buildMultiselectFixture()

    const output = await renderPdf({
      template,
      form: formDefinition,
      data: {
        recordTypes: [],
        status: 'inactive',
      },
      bindings,
    })

    const rendered = await PDFDocument.load(output)
    const form = rendered.getForm()

    expect(form.getCheckBox('recordTypes:clinic_visit_notes').isChecked()).toBe(false)
    expect(form.getCheckBox('recordTypes:lab_results').isChecked()).toBe(false)
    expect(form.getCheckBox('recordTypes:discharge_summary').isChecked()).toBe(false)
    expect(form.getCheckBox('status:inactive').isChecked()).toBe(true)
  })

  test('leaves all multiselect checkboxes unchecked when the field is undefined', async () => {
    const template = await buildMultiselectFixture()

    const output = await renderPdf({
      template,
      form: formDefinition,
      data: {
        // recordTypes deliberately omitted
        status: 'active',
      },
      bindings,
    })

    const rendered = await PDFDocument.load(output)
    const form = rendered.getForm()

    expect(form.getCheckBox('recordTypes:clinic_visit_notes').isChecked()).toBe(false)
    expect(form.getCheckBox('recordTypes:lab_results').isChecked()).toBe(false)
    expect(form.getCheckBox('recordTypes:discharge_summary').isChecked()).toBe(false)
  })
})
