/**
 * Codegen utilities for generating TypeScript declarations and modules from JSON artifacts
 *
 * These utilities enable type-safe usage of Paradoc artifacts loaded from JSON files
 * by generating either:
 * - .d.ts declaration files (for use alongside JSON imports)
 * - Full TypeScript modules (for ready-to-use typed exports)
 */

/**
 * Options for generating a TypeScript module from JSON
 */
export interface JsonToTsModuleOptions {
	/**
	 * The kind of artifact being converted
	 */
	artifactKind: 'form' | 'document' | 'checklist' | 'bundle'

	/**
	 * The export name for the artifact instance
	 * @example 'w9' will generate `export const w9 = para.form(...)`
	 */
	exportName: string

	/**
	 * Optional path to the JSON file (for import statement)
	 * If not provided, the schema will be embedded inline
	 */
	jsonImportPath?: string
}

/**
 * Converts a JSON value to its TypeScript literal type representation
 *
 * This generates types with `readonly` modifiers and literal values preserved,
 * enabling full type inference when the JSON is imported with a corresponding .d.ts file.
 *
 * @param value - The JSON value to convert
 * @param indent - Current indentation level (internal use)
 * @returns TypeScript type string with literal types
 *
 * @example
 * ```ts
 * jsonToLiteralType({ name: "w9", version: "1.0" })
 * // Returns:
 * // {
 * //   readonly "name": "w9";
 * //   readonly "version": "1.0";
 * // }
 * ```
 */
export function jsonToLiteralType(value: unknown, indent = 0): string {
	const spaces = '  '.repeat(indent)
	const innerSpaces = '  '.repeat(indent + 1)

	if (value === null) {
		return 'null'
	}

	if (value === undefined) {
		return 'undefined'
	}

	if (typeof value === 'string') {
		return JSON.stringify(value)
	}

	if (typeof value === 'number') {
		return String(value)
	}

	if (typeof value === 'boolean') {
		return String(value)
	}

	if (Array.isArray(value)) {
		if (value.length === 0) {
			return 'readonly []'
		}
		const items = value.map((v) => jsonToLiteralType(v, indent + 1))
		// For arrays, we use tuple type to preserve exact structure
		return `readonly [\n${innerSpaces}${items.join(`,\n${innerSpaces}`)}\n${spaces}]`
	}

	if (typeof value === 'object') {
		const entries = Object.entries(value)
		if (entries.length === 0) {
			return '{}'
		}
		const lines = entries.map(([k, v]) => {
			const key = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k)
			return `${innerSpaces}readonly ${key}: ${jsonToLiteralType(v, indent + 1)};`
		})
		return `{\n${lines.join('\n')}\n${spaces}}`
	}

	return 'unknown'
}

/**
 * Generates a TypeScript declaration file (.d.ts) content for a JSON value
 *
 * The generated declaration enables type-safe imports of JSON files by providing
 * literal types that TypeScript can use for inference.
 *
 * @param value - The JSON value to generate declarations for
 * @param moduleName - Optional module name (for documentation purposes)
 * @returns Complete .d.ts file content as a string
 *
 * @example
 * ```ts
 * const dts = jsonToDts(w9Schema, 'w9.json')
 * // Generates:
 * // declare const schema: {
 * //   readonly kind: "form";
 * //   readonly name: "w9";
 * //   ...
 * // };
 * // export default schema;
 * ```
 */
export function jsonToDts(value: unknown, moduleName?: string): string {
	const typeDefinition = jsonToLiteralType(value, 0)

	const lines: string[] = []

	// Add header comment
	lines.push('/**')
	lines.push(' * Auto-generated TypeScript declarations for JSON artifact')
	if (moduleName) {
		lines.push(` * Source: ${moduleName}`)
	}
	lines.push(' * ')
	lines.push(' * DO NOT EDIT - This file is generated by @paradoc/core codegen')
	lines.push(' */')
	lines.push('')

	// Declare the schema constant with literal types
	lines.push(`declare const schema: ${typeDefinition};`)
	lines.push('')
	lines.push('export default schema;')
	lines.push('')

	return lines.join('\n')
}

/**
 * Generates a complete TypeScript module that wraps a JSON artifact
 *
 * The generated module imports the JSON and creates a ready-to-use typed artifact instance.
 * This provides the best developer experience as users can import and use immediately.
 *
 * @param value - The JSON artifact value
 * @param options - Configuration for the generated module
 * @returns Complete TypeScript module content as a string
 *
 * @example
 * ```ts
 * const tsModule = jsonToTsModule(w9Schema, {
 *   artifactKind: 'form',
 *   exportName: 'w9',
 *   jsonImportPath: './w9.json'
 * })
 * // Generates:
 * // import schema from './w9.json';
 * // import { para } from '@paradoc/sdk';
 * //
 * // export const w9 = para.form(schema);
 * // export type W9Form = typeof w9;
 * // export type W9Payload = Parameters<typeof w9.fill>[0];
 * ```
 */
export function jsonToTsModule(value: unknown, options: JsonToTsModuleOptions): string {
	const { artifactKind, exportName, jsonImportPath } = options

	// Capitalize first letter for type names
	const typeName = exportName.charAt(0).toUpperCase() + exportName.slice(1)

	const lines: string[] = []

	// Add header comment
	lines.push('/**')
	lines.push(` * Auto-generated TypeScript module for ${artifactKind} artifact: ${exportName}`)
	lines.push(' * ')
	lines.push(' * DO NOT EDIT - This file is generated by @paradoc/core codegen')
	lines.push(' */')
	lines.push('')

	if (jsonImportPath) {
		// Import from JSON file
		lines.push(`import schema from '${jsonImportPath}';`)
	} else {
		// Embed the schema inline with `as const`
		const schemaJson = JSON.stringify(value, null, 2)
		// Indent the JSON for readability
		const indentedJson = schemaJson
			.split('\n')
			.map((line, i) => (i === 0 ? line : '  ' + line))
			.join('\n')
		lines.push(`const schema = ${indentedJson} as const;`)
	}

	lines.push(`import { para } from '@paradoc/sdk';`)
	lines.push('')

	// Create the artifact instance
	lines.push(`/**`)
	lines.push(` * ${typeName} ${artifactKind} artifact - ready to use`)
	lines.push(` */`)
	lines.push(`export const ${exportName} = para.${artifactKind}(schema);`)
	lines.push('')

	// Export useful types
	lines.push(`/**`)
	lines.push(` * Type of the ${exportName} ${artifactKind} instance`)
	lines.push(` */`)
	lines.push(`export type ${typeName}${capitalize(artifactKind)} = typeof ${exportName};`)
	lines.push('')

	// Add payload type for forms and checklists
	if (artifactKind === 'form' || artifactKind === 'checklist') {
		lines.push(`/**`)
		lines.push(` * Payload type for filling the ${exportName} ${artifactKind}`)
		lines.push(` */`)
		lines.push(`export type ${typeName}Payload = Parameters<typeof ${exportName}.fill>[0];`)
		lines.push('')
	}

	return lines.join('\n')
}

/**
 * Capitalize first letter of a string
 */
function capitalize(str: string): string {
	return str.charAt(0).toUpperCase() + str.slice(1)
}
