export { renderDocx } from './docx/render'
export type { DocxRenderOptions, DocxSignatureOptions, RenderDocxOptions } from './docx/render'
export { docxRenderer } from './docx/renderer'
export type { DocxRendererOptions } from './docx/renderer'
export { checkDocxTemplate } from './template/check'
export type { DocxCheckOptions } from './template/check'
export { TemplateError } from './template/errors'
export type { TemplateDiagnostic, TemplatePosition } from './template/errors'
